## Database conection and login
#spring.datasource.url=jdbc:postgresql://localhost:5455/easysell
#spring.datasource.username=app
#spring.datasource.password=app2022
#
#  #database name
#spring.jpa.database=postgresql
#
#  #thymeleaf configs
#spring.thymeleaf.mode=HTML
#spring.thymeleaf.cache=false
#
#  #spring dev tools config
#spring.devtools.restart.enabled=true
#spring.devtools.restart.additional-paths=src
#
#  #spring hibernate
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
#spring.jpa.hibernate.ddl-auto=update
#
#
#server:
#  error:
#    include-stacktrace: on_param
#
#spring:
#  application:
#    name: springboot
#  datasource:
#    url: jdbc:postgresql://localhost:5455/easysell
#    username: app
#    password: app2022
#  jpa:
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true
#    hibernate:
#      ddl-auto: update
#
#  thymeleaf:
#    mode: htm
